title: "Your Name - Web3 UX Designer"
description: "Crafting intuitive experiences for the decentralized web"
url: "https://kugothepup.github.io"
baseurl: "/glowing-carnival"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/

# Collections for case studies
collections:
  projects:
    output: true
    permalink: /projects/:name/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Web3 specific configs
ens_domain: "yourname.eth"
wallet_address: "0x..." # Optional
social:
  twitter: "yourhandle"
  linkedin: "yourprofile"
  github: "Kugothepup"

# Exclude from processing
exclude:
  - package.json
  - package-lock.json
  - node_modules
  - tailwind.config.js
  - postcss.config.js